const fs = require('fs');
const path = require('path');

// Raw CSV text provided directly by the user in the prompt
const rawCsv = `ID,Nom,Latitude,Longitude,Catégorie,Description (FR),Description (EN),Narration Text (FR),Narration Text (EN),Article Mystere,Image URL
1,Cathédrale Saint-Étienne - L'Athanor de Pierre,47.0805,2.3991,CATHEDRAL,"Chef-d'œuvre gothique majeur classé à l'UNESCO, célèbre pour l'absence de transept, sa verticalité saisissante et ses mystères hermétiques.","UNESCO World Heritage Gothic masterpiece known for its unique transept-less design, immense verticality, and hermetic mysteries.","Vous vous trouvez face à l'un des plus grands chefs-d'œuvre de l'art gothique mondial : la cathédrale Saint-Étienne de Bourges, inscrite au Patrimoine Mondial de l'UNESCO depuis 1992. Elle accueille chaque année plus de six cent mille visiteurs.

Sa construction a débuté en 1195, sur l'ordre de l'archevêque Henri de Sully, à l'emplacement d'une ancienne cathédrale romane détruite par un incendie. Elle fut consacrée le treize mai 1324. Ce vaisseau de pierre mesure plus de cent mètres de long et culmine à près de cinquante mètres de hauteur. Visible à trente kilomètres à la ronde sur la plaine berrichonne, elle trône comme un phare au sommet de la colline historique d'Avaricum.

L'une de ses singularités absolues : elle est l'une des seules cathédrales gothiques de France à ne posséder aucun transept. Cette conception audacieuse crée une nef ininterrompue aux proportions magistrales. Ses deux tours inégales, que l'écrivain Huysmans décrivit comme ""boitant dans le ciel"", encadrent cinq portails sculptés dont le portail du Jugement Dernier, chef-d'œuvre de la sculpture médiévale.

Ses vitraux du treizième siècle, parmi les plus beaux de France, filtrent une lumière colorée sur plus de cinq cents mètres carrés de surface vitrée.

Sachez que Bourges est depuis la fin du Moyen Âge considérée comme l'une des capitales européennes de l'alchimie. Selon une tradition ésotérique persistante, la cathédrale elle-même serait un immense athanor, le four alchimique des adeptes du Grand Œuvre. Son quartier cache encore la mystérieuse rue du Mauvais Secret, la rue de l'Alchimie et la Tour du Diable. Les bâtisseurs de ce monument auraient gravé dans la pierre les secrets de la transmutation. À vous de les chercher.","You stand before the majestic Saint-Étienne Cathedral of Bourges. Look up at its five unique portals. In medieval esotericism, this continuous nave without a transept symbolizes the soul's ascent toward divine illumination. For centuries, hermetic scholars have read this architecture as a monumental vessel of transmutation.","La cathédrale de Bourges n'est pas seulement un temple de dévotion chrétienne : elle est considérée par l'ésotérisme comme un immense athanor de pierre. Érigée au tournant des XIIe et XIIIe siècles sans transept – cas unique pour une cathédrale de cette envergure – elle offre une nef ininterrompue créant un couloir d'ondes vibratoires singulier. Au portail du Jugement Dernier, saint Michel pèse les âmes avec une balance dont l'équilibre défie les lois terrestres. Sous la rose occidentale, les alchimistes du Berry lisaient les étapes de la transmutation du plomb en or spirituel. Dans la pénombre du déambulatoire, des motifs géométriques secrets cachés dans les vitraux du XIIIe siècle contiendraient la clé de l'harmonisation tellurique de la colline sacrée d'Avaricum.",https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Bourges_Cathedrale_Saint-Etienne_01.jpg/800px-Bourges_Cathedrale_Saint-Etienne_01.jpg
2,Palais Jacques Cœur - L'Énigme de l'Argentier Alchimiste,47.0844,2.3929,PALACE,"Le plus fastueux logis civil gothique de France, érigé par le grand trésorier de Charles VII, recelant de secrets symboles alchimiques.","France's most luxurious Gothic civil palace, built by King Charles VII's financier, full of secret alchemical symbols.","Devant vous s'élève la plus spectaculaire demeure civile gothique de France : le Palais Jacques Cœur, construit entre 1443 et 1451 par l'homme le plus puissant du royaume après le roi lui-même.

Jacques Cœur est né à Bourges vers 1400, fils d'un modeste marchand de pelleterie. Après quelques démêlés avec la justice pour faux-monnayage, il va connaître une ascension sociale foudroyante. Devenu Grand Argentier du roi Charles Sept, Maître des Monnaies et armateur des galées de France, il bâtit un empire commercial reliant Paris au Levant. Sa devise gravée sur les murs résume son ambition : « À vaillants cœurs, riens impossible. »

Sa ""Grant' Maison"", comme il l'appelait lui-même, est une résidence de quatre mille mètres carrés, composée de quarante-trois salles, huit escaliers, et deux façades radicalement différentes : l'une austère et fortifiée côté rue, l'autre d'une luxuriance gothique flamboyante côté cour. Elle est édifiée sur la muraille gallo-romaine de l'antique Avaricum.

Mais Jacques Cœur ne put jamais habiter son palais. Arrêté en 1451, victime des jalousies de la cour, il mourut en exil en 1456, avant même que son palais soit achevé. Charles Sept en prit possession et ne le rendit à ses enfants qu'après sa mort.

Curiosité troublante : dès le dix-septième siècle, des médecins et savants attribuaient la fortune de Jacques Cœur à la possession de la Pierre Philosophale. Son palais recèle effectivement des sculptures étranges — un pélican nourrissant ses petits de son sang, des cerfs ailés, un fou qui tient sa bouche fermée par un cadenas — autant de symboles hermétiques que Fulcanelli lui-même a commentés. Propriété de l'État depuis 1923, il est géré par le Centre des Monuments Nationaux.","Welcome to the Jacques Cœur Palace. 'To valiant hearts, nothing is impossible.' How did a humble furrier's son become the wealthiest man in Europe within years? Legend claims Jacques Cœur held the secret of the Philosopher's Stone.","Jacques Cœur est l'une des figures les plus fascinantes de l'histoire de France. Grand Argentier du roi Charles VII, maître des monnaies, diplomate et armateur, il finance la reconquête du royaume contre les Anglais. Mais d'où provenait son or inépuisable ? La légende tenace veut qu'il fût initié aux arcanes de l'alchimie orientale lors de ses voyages au Levant. En observant attentivement la façade et les cheminées monumentales du palais, on découvre des arbres aux fruits d'or, des coquilles Saint-Jacques couplées à des cœurs enflammés (symboles du creuset et de la matière première), ainsi que des représentations du pélican nourrissant ses petits de son sang, allégorie hermétique de la Pierre au rouge. De nombreux souterrains partaient des caves vers les remparts, utilisés lors de sa disgrâce soudaine en 1451.",https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Palais_Jacques_C%C5%93ur_Bourges_FR18_01.jpg/800px-Palais_Jacques_C%C5%93ur_Bourges_FR18_01.jpg
3,Hôtel Lallemant - Le Chef-d'œuvre de l'Alchimie Universelle,47.0847,2.3967,PALACE,"Hôtel particulier Renaissance renfermant le célèbre plafond sculpté aux 30 caissons ésotériques, immortalisé par Fulcanelli.","Renaissance mansion containing the famous coffered ceiling of 30 esoteric caissons, deciphered by Fulcanelli.","Vous entrez dans le lieu que les adeptes de la philosophie hermétique considèrent comme le sanctuaire alchimique le plus précieux d'Europe occidentale : l'Hôtel Lallemant.

Construit entre 1495 et 1518 pour les frères Jean et Robert Lallemant, riches marchands de Bourges, cet hôtel particulier constitue un fleuron de la première Renaissance française. Sa particularité unique au monde : le plafond de son oratoire privé est orné de trente caissons sculptés dont la signification fait encore débat entre historiens et ésotéristes.

En 1926, le mystérieux alchimiste Fulcanelli leur consacra un chapitre entier de son ouvrage Le Mystère des Cathédrales. Pour lui, ces trente caissons forment un traité alchimique complet taillé dans la pierre, décrivant pas à pas les opérations philosophiques du Grand Œuvre. On y reconnaît une colombe symbolisant l'esprit, un livre aux sept sceaux brûlant dans un brasier, un enfant soufflant sur un athanor, un faucon attaché à un cep de vigne et une ruche bourdonnante.

Curiosité historique piquante : depuis deux siècles, le musée conserve une mèche de cheveux bruns attribuée à Agnès Sorel, la première maîtresse officielle d'un roi de France, Charles Sept. Sauf que Agnès Sorel était... blonde. Ce petit mystère capillaire reste inexpliqué.

L'hôtel a été acquis par la ville de Bourges en 1826 et abrite depuis 1951 le Musée des Arts Décoratifs. Mais quelle fraternité secrète se réunissait ici à la fin du quinzième siècle ? Les historiens débattent encore. Une chose est certaine : en cinq cents ans, personne n'a encore trouvé la clé définitive de ce plafond extraordinaire.","Enter the sanctum of European hermeticism: the Hôtel Lallemant. This early Renaissance jewel hides an alchemical codex carved in limestone. Its private oratory ceiling contains 30 sculpted caissons decoded by modern esoteric masters.","L'Hôtel Lallemant est sans conteste le monument alchimique le plus réputé d'Europe occidentale. En 1926, le mystérieux maître Fulcanelli lui consacra plusieurs chapitres entiers de son livre 'Le Mystère des Cathédrales'. Construit par les frères Jean et Robert Lallemant à la suite du grand incendie de 1487, l'édifice est un hommage aux adeptes du Grand Œuvre. Dans le minuscule oratoire privé, le plafond sculpté de 30 caissons révèle la suite exacte des opérations philosophiques : la colombe de l'esprit, le lion céleste, l'épervier attaché à un cep de vigne, la ruche bourdonnante et surtout la figure d'un enfant qui souffle sur un athanor tout en tenant une coquille. Les historiens continuent de débattre : quelle fraternité secrète se réunissait dans ces salles voûtées ?",https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/H%C3%B4tel_Lallemant_Bourges_facade.jpg/800px-H%C3%B4tel_Lallemant_Bourges_facade.jpg
4,L'Horloge Astronomique de Bourges (1424),47.0807,2.3986,CATHEDRAL,"La plus ancienne horloge astronomique de France conservée intacte, conçue par le chanoine Jean Fusoris sur ordre de Charles VII.","France's oldest preserved astronomical clock, designed by canon Jean Fusoris in 1424 by royal order of Charles VII.","Levez les yeux sur ce chef-d'œuvre de la mécanique médiévale : l'Horloge Astronomique de Bourges, conçue en novembre 1424 par le chanoine Jean Fusoris. Elle est considérée comme la plus ancienne horloge astronomique encore conservée de France.

Son histoire est liée à l'un des moments les plus sombres de l'histoire française. En 1424, Bourges est la résidence du roi Charles Sept, que ses adversaires surnomment cruellement le ""Petit Roi de Bourges"" : il ne règne que sur un maigre territoire centré sur cette ville, pendant que les Anglais et les Bourguignons occupent le reste du royaume. C'est dans ce contexte de guerre de Cent Ans que Charles Sept offre cet instrument prodigieux à ses fidèles sujets berruyers, pour célébrer le baptême de son fils le dauphin, futur Louis Onze.

Jean Fusoris était un personnage hors norme : astronome, mathématicien, médecin, constructeur d'astrolabes, il avait même été condamné à l'exil pour avoir vendu des instruments astronomiques aux Anglais avant d'être grâcié. Son horloge est un prodige d'ingénierie : trois cent vingt-trois pièces s'assemblent dans un buffet de six mètres de hauteur. Elle indique l'heure, les phases de la Lune, la position du Soleil, les constellations du Zodiaque, le quantième du mois et les heures babyloniennes. Sa précision stupéfiante : un décalage d'une seule seconde tous les cent cinquante ans.

Le mécanisme original installé en 1424 sur le jubé nord de la cathédrale fut en partie restauré et remplacé par une copie exacte en 1994. L'original est aujourd'hui préservé et exposé dans la cathédrale. Une merveille qui traversa six siècles et plusieurs révolutions.","This mechanical masterpiece was presented in 1424 by Charles VII. Observe its dial calculating lunar phases, solar coordinates, and astrological constellations, reflecting the medieval universe's harmonic secrets.","Conçue par le mathématicien, médecin et astronome Jean Fusoris en 1424, l'Horloge Astronomique de Bourges est un prodige technologique qui a traversé les siècles. Mais au-delà de sa prouesse d'horlogerie, elle servait de guide astrologique à la cour de Charles VII réfugiée à Bourges durant la guerre de Cent Ans. À cette époque, aucun acte politique ou militaire n'était entrepris sans consulter les augures et l'alignement des corps célestes. L'aiguille solaire à visage d'or pointe les 24 heures médiévales tandis qu'une aiguille lunaire tourne dans un disque étoilé gravé selon les traditions ptolémaïques. Une légende raconte que Fusoris y aurait caché un calendrier perpétuel prédisant les grandes crises de la monarchie.",https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Bourges_horloge_astronomique_01.jpg/800px-Bourges_horloge_astronomique_01.jpg
5,Les Marais de Bourges - Le Territoire de la Vouivre,47.0885,2.4045,NATURE,"135 hectares de parcelles potagères entourées d'eau en plein cœur de ville, berceau de mythes et de créatures féeriques.","135 hectares of idyllic marshland plots wrapped in shimmering canals, fertile ground for folklore and mythical creatures.","Abandonnez le temps d'un instant les rues pavées du vieux Bourges et pénétrez dans un univers parallèle qui existe en plein cœur de la ville : les Marais de Bourges. Cent trente-cinq hectares de jardins potagers cultivés par quelques mille deux cents propriétaires berruyers, traversés de canaux silencieux où glissent des barques traditionnelles à fond plat.

Cette zone humide façonnée par l'Yèvre et la Voiselle est l'une des plus anciennes de France. Dès l'Antiquité, Jules César, lors du siège d'Avaricum en 52 avant Jésus-Christ, décrit ces marécages comme ""nauséabonds et insalubres"" — ils lui coûtèrent plusieurs semaines de campagne. C'est justement là leur force militaire : ils formaient une ceinture défensive naturelle autour de la cité gauloise.

À partir du huitième siècle, les communautés religieuses et les moines commencèrent à creuser des canaux et à aménager des parcelles cultivables. Au dix-septième siècle, les Jésuites achetèrent les marais et les louèrent à des particuliers, inaugurant une tradition maraîchère qui perdurera jusqu'au vingtième siècle. Aujourd'hui, avec les hortillonnages d'Amiens et le marais de Saint-Omer, ce sont l'un des derniers marais maraîchers de France.

Au-delà de leur intérêt écologique et historique, les Marais de Bourges sont peuplés de légendes berrichonnes. Les anciens racontaient qu'au crépuscule, quand la brume montait des eaux sombres, on pouvait apercevoir la Vouivre : un serpent fabuleux et ailé, doté d'un rubis lumineux incrusté au front. La Vouivre hantait les eaux dormantes de tout le Berry, créature à la fois terrifiante et fascinante. Vous pouvez encore découvrir ces marais en barque guidée par un ""bourdeur"" local.","Step into the green labyrinth of Bourges' marshes. Carved by canals that once shielded ancient Avaricum, this watery realm is steeped in Berry folklore, home of the Vouivre serpent creature.","Les Marais de Bourges constituent un écosystème unique en Europe. À l'origine zone marécageuse stratégique qui tint en échec les légions de Jules César en 52 avant J.-C., ils furent asséchés et aménagés au Moyen Âge par les moines et les maraîchers locaux. Ce monde de canaux et de 'plaques' (barques traditionnelles à fond plat) possède son panthéon de légendes populaires berrichonnes. Les légendes orales rapportent la présence d'esprits des eaux, de feux follets mystificateurs guidant les ivrognes vers la vase, et de la célèbre Vouivre, créature ailée mi-femme mi-dragon qui dépose son œil de rubis sur la berge avant de plonger.",https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Marais_de_Bourges_-_Canal.jpg/800px-Marais_de_Bourges_-_Canal.jpg
6,Hôtel Cujas & Musée du Berry - Secrets d'Avaricum,47.0838,2.3948,MUSEUM,"Somptueux hôtel particulier en briques rouges et calcaire, abritant les stèles gauloises et trésors archéologiques du Berry.","Splendid red brick and limestone mansion home to Gallo-Roman stelae and archaeological treasures of ancient Avaricum.","Vous voici devant l'Hôtel Cujas, chef-d'œuvre de la première Renaissance berrichonne, construit au début du seizième siècle pour un riche marchand florentin du nom de Durand Salvi. L'édifice a conservé le nom de son plus illustre résident, le célèbre juriste Jacques Cujas, qui y vécut entre 1585 et 1590. Depuis 1892, il abrite le Musée du Berry, véritable porte d'entrée dans les profondeurs des âges.

Le rez-de-chaussée déploie des collections archéologiques exceptionnelles couvrant plusieurs millénaires. Les Bituriges Cubes, le peuple gaulois qui donna son nom à Bourges — ""Bituriges"" signifiant littéralement ""les rois du monde"" — habitaient cette colline avant l'arrivée des Romains. En 52 avant Jésus-Christ, Jules César la décrivit dans sa Guerre des Gaules comme ""la plus belle ville de toute la Gaule, ou peu s'en faut"". Malgré une résistance acharnée, il la prit et massacra presque toute la population.

La salle lapidaire est particulièrement saisissante : elle rassemble plus de deux cent vingt stèles funéraires gallo-romaines, un record absolu pour la région, ainsi que des mosaïques, des peintures murales et une vaisselle de bronze et de verre révélant l'opulence d'Avaricum, capitale de la province d'Aquitaine sous l'Empire romain.

Clou du musée : une véritable momie égyptienne, le prêtre Djehdor, datant du quatrième siècle avant Jésus-Christ. Comment cette momie a-t-elle abouti à Bourges ? Par un méandre des collections et achats du dix-neuvième siècle. Également exposés : les pleurants d'albâtre du tombeau du Duc Jean de Berry, les vitraux de l'ancienne Sainte-Chapelle ducale et les tableaux de Jean Boucher, maître de la peinture berrichonne du dix-septième siècle.","Hôtel Cujas houses the archaeological soul of Bourges. Wander through collections featuring rare Celtic votive relics, sacred roman bronzes, and artifacts from pre-Roman Bituriges sanctuaries.","L'Hôtel Cujas est bâti sur l'emplacement même de sanctuaires antiques d'Avaricum, la capitale des Bituriges Cubes ('les rois du monde' en langue celtique). Lors des fouilles du XIXe siècle dans les fondations de l'hôtel et des rues environnantes, les archéologues ont mis au jour une quantité impressionnante de stèles sculptées représentant des artisans défunts, mais aussi d'étranges divinités sylvestres et des ex-voto anatomiques en bronze. Le musée conserve également une mystérieuse collection d'amulettes de protection et les pleurants d'albâtre du tombeau de Jean de Berry, témoins du deuil royal et des rituels nécrophores médiévaux.",https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/H%C3%B4tel_Cujas_Bourges.jpg/800px-H%C3%B4tel_Cujas_Bourges.jpg
7,La Crypte de la Cathédrale - L'Église Basse Oubliée,47.0809,2.3995,CATHEDRAL,"La plus vaste crypte gothique d'Europe, chef-d'œuvre de substruction soutenant le chevet au-dessus des anciens fossés romains.","The largest Gothic crypt in Europe, supporting the cathedral's apse over ancient Gallo-Roman defensive ditches.","Descendez maintenant dans les entrailles de la cathédrale pour découvrir son secret le mieux gardé : la crypte, ou Église Basse, un espace souterrain d'une rare puissance émotionnelle.

Pour rejoindre cette crypte, vous allez faire quelque chose d'inhabituel : monter des marches. En effet, la cathédrale fut construite sur l'ancienne muraille gallo-romaine, qui crée une différence de niveau de six mètres entre les deux extrémités de l'édifice. La crypte, réalisée dès 1195, fut condamnée à la fin du douzième siècle lors de la reconstruction de la cathédrale, puis redécouverte en 1757. Pendant cent cinquante ans, on n'y accédait qu'en soulevant deux dalles situées dans le déambulatoire.

Sa pièce maîtresse est le gisant du Duc Jean de Berry. Ce monument de marbre blanc sculpté par l'artiste flamand Jean de Cambrai représente le duc couronné, les mains croisées, les pieds reposant sur un ours endormi muselé. Jean de Berry était l'une des personnalités les plus fascinantes de la France médiévale : fils de Jean le Bon, frère de Charles Cinq, oncle de Charles Six, grand mécène et commanditaire des célèbres Très Riches Heures du Duc de Berry. Il mourut en 1416 à l'âge de soixante-seize ans. Ses cendres ? Personne ne sait ce qu'elles sont devenues après la Révolution. Mystère total.

La crypte conserve également les douze vitraux de l'ancienne Sainte-Chapelle ducale, une Mise au Tombeau du seizième siècle dans sa rotonde, et les extraordinaires fragments du jubé gothique du treizième siècle. Détail troublant : le fond de la crypte, selon plusieurs géobiologistes, se situerait sur un puissant nœud tellurique d'énergie magnétique. Vous ressentirez peut-être quelque chose d'indéfinissable en vous y attardant.","Descend into the underground foundations of the cathedral: the lower church. Spanning colossal stone vaults designed to span the Roman ramparts, it shelters the tomb of Duke Jean de Berry.","Cette 'crypte' n'en est pas une au sens liturgique strict : c'est une église basse entièrement voûtée, inondée par une lumière tamisée venue de meurtrières ouvertes sur le jardin. Sa construction audacieuse a permis d'étendre la cathédrale au-delà de l'enceinte romaine fortifiée d'Avaricum. Au centre trône le gisant de marbre blanc de Jean de France, duc de Berry, mécène des célèbres 'Très Riches Heures'. Les récits anciens mentionnent que sous les dalles de l'église basse courait une source sacrée druidique, christianisée sous le vocable de Notre-Dame-de-Sous-Terre, dont l'eau était réputée guérir les fièvres et chasser les possessions démoniaques.",https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Crypte_Cathedrale_Bourges.jpg/800px-Crypte_Cathedrale_Bourges.jpg
8,Remparts Gallo-Romains & Tour des Fiefs,47.0818,2.4012,SOUTERRAINS,"L'impressionnante muraille du IVe siècle bâtie en pierres de taille antiques de réemploi pour fortifier le haut plateau berruyer.","4th-century Roman fortress walls constructed with repurposed monumental antique stonework across Bourges ridge.","Ces colossales assises de pierre que vous apercevez le long de la promenade sont les vestiges des remparts gallo-romains de Bourges, construits au cours du troisième siècle après Jésus-Christ. Ils constituent l'une des meilleures sections de fortification antique conservées en France.

Leur construction répond à l'urgence des invasions barbares menaçant l'Empire romain. À cette époque, Bourges, rebaptisée Biturigae, est capitale de la province d'Aquitaine Première, l'une des provinces les plus importantes du monde romain. Pour la protéger, les ingénieurs de l'Empire élèvent un mur d'enceinte colossal : deux virgule cinq kilomètres de long, de trois à six mètres d'épaisseur à la base, percé de quatre portes monumentales et flanqué de quarante-six tours défensives d'un diamètre de dix mètres chacune.

Particularité fascinante : les pierres utilisées pour bâtir ce rempart sont en grande partie des blocs récupérés sur d'anciens temples, thermes et monuments publics de la cité gallo-romaine. Les constructeurs ont recyclé le passé pour bâtir le futur.

Autre secret de ces murs : ils portent en eux les fondations invisibles de plusieurs édifices célèbres. Le Palais Jacques Cœur repose partiellement sur ces remparts. L'Hôtel des Échevins et l'Hôtel Lallemant sont bâtis à cheval sur cette même muraille. La cathédrale Saint-Étienne elle-même utilise les anciens soubassements romains.

Au quatrième siècle, avant même que les Francs prennent le contrôle de la Gaule, ces murs ont résisté aux premières vagues de migrations barbares. Ils survivèrent jusqu'au douzième siècle, quand Philippe Auguste les fit remplacer par une nouvelle enceinte médiévale. Vous en observez aujourd'hui les plus beaux témoins rescapés.","Gaze upon these colossal 4th-century Roman battlements. Over fifty defensive bastions guarded this crest. Builders re-used carved stones from demolished pagan temples, turning the wall into a cryptic stone archive.","L'enceinte gallo-romaine de Bourges mesure près de deux kilomètres de périmètre et atteint par endroits plus de cinq mètres d'épaisseur. Son secret le plus stupéfiant réside dans ses fondations : menacés par les vagues d'invasions germaniques, les habitants d'Avaricum démontèrent à la hâte les temples, théâtres et mausolées de la plaine pour les sceller dans le mortier de la muraille. On peut encore distinguer des corniches sculptées, des bustes de déesses de la fécondité et des inscriptions latines incrustées à l'envers, comme pour désacraliser les anciens cultes ou créer un bouclier magique protecteur contre les assaillants.",https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Rempart_gallo-romain_Bourges.jpg/800px-Rempart_gallo-romain_Bourges.jpg
9,Église Notre-Dame & Le Puits du Griffon,47.0852,2.3961,CATHEDRAL,"L'église paroissiale des marchands drapiers et le puits séculaire ayant miraculeusement abreuvé la population assiégée.","Parish church of the wool merchants next to the historic Griffin Well that saved the city during past sieges.","L'église Notre-Dame que vous avez devant vous ne ressemble à aucune autre de Bourges. Et pour cause : elle fut entièrement reconstruite après l'un des événements les plus catastrophiques de l'histoire de la ville — le grand incendie de la Madeleine, le vingt-deux juillet 1487.

Ce sinistre est le pire que Bourges ait jamais connu. En une seule nuit de juillet, plus d'un tiers de la ville fut réduit en cendres. Les quartiers de Saint-Ambroix, Saint-Bonnet, la place Gordaine, les rues Mirebeau, Coursarlon et Bourbonnoux disparurent dans les flammes. L'église Notre-Dame, comme tant d'autres, fut détruite. Ce drame explique pourquoi tant de maisons à colombages de la ville datent de la fin du quinzième siècle : elles furent toutes reconstruites après le sinistre.

Juste à côté de l'église se trouve une curiosité architecturale qui intrigue les promeneurs depuis des siècles : le Puits du Griffon. Ce puits médiéval tire son nom du griffon, créature mythologique mi-lion mi-aigle, gardienne des trésors dans les traditions médiévales. Pourquoi un tel nom pour un simple puits d'eau ? La légende locale veut qu'au fond de ce puits se cachent des galeries secrètes reliées aux souterrains de la ville haute.

Les amateurs de géographie sacrée notent que l'église Notre-Dame s'inscrit dans un alignement particulier avec la cathédrale et plusieurs autres édifices religieux de Bourges, formant ce que certains chercheurs qualifient de ""triangle hermétique"" du vieux Bourges. Coïncidence ou intention délibérée des bâtisseurs médiévaux ? Cette question reste ouverte.","Notre-Dame church was lovingly rebuilt after the catastrophic Great Fire of 1487. Outside stands the legendary Griffin Well, whose subterranean spring supplied cool water throughout historic sieges.","L'église Notre-Dame conserve de sublimes verrières Renaissance et une chaire en chêne ouvragée ornée d'énigmes iconographiques. Mais c'est le Puits du Griffon attenant qui hante la mémoire locale : selon les chroniques du Berry, pendant le siège terrible mené en 1152 par le roi Louis VII, tous les puits de la ville haute avaient été empoisonnés ou asséchés sauf celui-ci, alimenté par une résurgence mystérieuse descendant des forêts de Menetou. Les compagnons bâtisseurs y avaient sculpté un griffon – créature mi-aigle mi-lion symbolisant la double nature du Christ et la garde des trésors cachés.",https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Eglise_Notre-Dame_Bourges.jpg/800px-Eglise_Notre-Dame_Bourges.jpg
10,Tour des Échevins (Musée Estève),47.0841,2.3958,MUSEUM,"Ancien hôtel de ville de la Renaissance tardive doté d'une vertigineuse tourelle d'escalier hélicoïdale aux motifs cabalistiques.","Late Gothic & Renaissance Town Hall boasting an exquisite spiral stair tower inscribed with curious guild motifs.","L'élégante tour-escalier octogonale que vous admirez marque l'entrée de l'Hôtel des Échevins, premier siège officiel de la municipalité de Bourges, construit à partir de 1489. Le terme ""échevins"" désigne les magistrats municipaux qui assistaient le maire dans le gouvernement de la ville.

Cet hôtel particulier de style gothique flamboyant est directement inspiré du Palais Jacques Cœur voisin. Comme lui, il est édifié sur la muraille gallo-romaine. Le corps de logis principal date de la fin du quinzième siècle. En 1623, l'architecte berruyer Jean Lejuge y ajouta une galerie Renaissance reliant la tourelle au bâtiment principal — exemple rarissime d'architecture classique à Bourges.

Pendant presque deux siècles, de 1489 à 1682, c'est ici que le conseil municipal délibérait, que les archives de la ville étaient gardées, et que se prenaient les décisions qui façonnaient la cité. En 1682, le conseil déménagea au Palais Jacques Cœur.

L'Hôtel des Échevins connut ensuite une existence mouvementée : bien national à la Révolution, petit lycée au dix-neuvième siècle, il fut enfin classé Monument Historique en 1886 et entièrement restauré cent ans plus tard pour devenir le Musée Estève.

Ce musée est une véritable surprise : il présente l'œuvre magnifique du peintre abstrait Maurice Estève, né en 1904 à Culan dans le Cher et mort en 2001. Peintre autodidacte influencé par Cézanne et les Surréalistes, il offrit en 1985 à la ville de Bourges une donation extraordinaire de deux cents œuvres — huiles, aquarelles, collages, tapisseries. Dans la cour, une sculpture d'Alexander Calder vous accueille. Estève écrivait : ""C'est la lumière que je cherche à travers la couleur.""","Behold the Échevins Mansion, built in 1489 as the seat of municipal magistrates. Its octagonal stone spiral tower stands as an archetype of sacred stonemason geometry.","Construite immédiatement après l'incendie dévastateur de 1487, la Tour des Échevins était le centre nerveux du pouvoir civil berruyer face au pouvoir tout-puissant des archevêques. Les maîtres maçons de la corporation y ont inséré des symboles de compagnonnage hermétique : coquilles, feuilles d'acanthe tournoyantes, gargouilles protectrices et clés de voûte étoilées. Aujourd'hui consacrée à l'œuvre du peintre abstrait Maurice Estève, elle offre une résonance unique entre les formes médiévales et la géométrie picturale moderne.",https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Bourges_hotel_des_echevins_tour.jpg/800px-Bourges_hotel_des_echevins_tour.jpg
11,Rue Bourbonnoux & La Maison des Trois Flacons,47.0831,2.3995,ALCHIMIE,"Rue médiévale emblématique aux maisons à pans de bois, refuge des alchimistes, herboristes et apothicaires de la cour royale.","Iconic cobblestone medieval street lined with half-timbered houses, former home to apothecaries and alchemists.","La rue Bourbonnoux est l'une des artères les plus pittoresques et les plus vivantes du vieux Bourges. Sa longue histoire remonte au Moyen Âge, quand elle constituait l'une des principales voies d'accès au marché couvert de la ville.

Parcourez-la en levant les yeux. Vous découvrirez un véritable musée à ciel ouvert de l'architecture médiévale à pans de bois. Bourges conserve en effet quelques quatre cent quarante maisons à colombages du quinzième et seizième siècle — l'un des patrimoines de bois les plus riches de la région Centre-Val de Loire. La plupart furent reconstruites après le grand incendie de 1487, qui ravagea une grande partie du quartier.

Le joyau de la rue est sans conteste la ""Maison des Trois Flacons"", également appelée ""Maison des Trois Flûtes"" selon les interprétations. Sa façade est ornée d'un extraordinaire poteau-cornier, la poutre d'angle sculptée qui marque le coin de la maison. Ces poteaux-corniers étaient au Moyen Âge de véritables vitrines publicitaires pour les artisans et marchands qui habitaient la demeure. Celui-ci est parmi les plus finement ciselés de Bourges.

La rue Bourbonnoux tient son nom d'une enseigne médiévale — une maison au bœuf bourbonnais. Elle reliait autrefois la Porte Gordaine au quartier Saint-Bonnet et voyait défiler quotidiennement marchands, pèlerins, artisans et clercs. On raconte que lors des grandes épidémies de peste qui frappèrent Bourges au Moyen Âge, des processions de pénitents descendaient cette rue en chantant des litanies funèbres aux flambeaux. L'écho de ces cortèges semble parfois encore habiter les vieilles pierres.","Stroll down Rue Bourbonnoux, among the most evocative preserved medieval alleyways in France. Under timber jetties, historical apothecaries brewed herbal elixirs and alchemical waters.","La rue Bourbonnoux suit le tracé exact des anciennes courtines médiévales. Aux XIVe et XVe siècles, elle accueillait les ateliers des fabricants d'élixirs, maîtres-vitriers de la cathédrale et apothicaires de Jean de Berry. Au numéro 27 se tenait selon la tradition 'L'Officine aux Trois Flacons' : trois récipients de verre rouge, vert et doré symbolisant les trois phases du Grand Œuvre alchimique (Œuvre au Noir, au Blanc et au Rouge). Des inscriptions cabalistiques découvertes sur les linteaux de chêne rappellent que la recherche de la santé universelle et de la transmutation animait quotidiennement ce quartier.",https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Bourges_Rue_Bourbonnoux.jpg/800px-Bourges_Rue_Bourbonnoux.jpg
12,Place Gordaine - Théâtre des Sabbats et Mystères,47.0858,2.3989,SORCELLERIE,"Le cœur vibrant du vieux Bourges, bordé de maisons à colombages du XVe siècle et théâtre des légendes berrichonnes.","Vibrant medieval square ringed with fairy-tale timbered homes, scene of market assemblies and midnight lore.","Vous voici en plein cœur du Bourges médiéval sur la Place Gordaine. Ce petit espace charmant entouré de maisons à colombages est l'un des témoins les plus vivants de ce qu'était la vie urbaine au Moyen Âge.

Son nom est directement hérité de l'Antiquité romaine. La Porte Gordaine — en latin Gordonia — était l'une des quatre portes monumentales perçant le rempart gallo-romain d'Avaricum. Elle ouvrait sur la route de Sancerre. Au quinzième siècle, cette porte donnait son nom à toute la place qui se développait à ses pieds.

Au Moyen Âge, la Place Gordaine était l'un des lieux de marché les plus animés de Bourges. Changeurs de monnaie, bouchers et poissonniers y tenaient boutique. L'Yèvrette, rivière artificielle créée avant le onzième siècle, traversait alors la place, permettant aux artisans utilisant l'eau d'exercer leur métier. La première mention écrite de ce cours d'eau remonte à l'an 1012. Les boucheries et poissonneries furent démolies en 1871 et un square aménagé entre 1889 et 1891.

Bourges fut longtemps surnommée par ses voisins de province ""la terre des sorciers"". Une légende tenace voulait autrefois qu'à certaines nuits du calendrier astronomique — particulièrement la nuit de la Saint-Jean et celle de Walpurgis — les sorciers et sorcières du Berry se réunissaient en ce lieu pour tenir leur sabbat. Le Berry fut pendant des siècles réputé pour ses guérisseurs, ses ""meneurs de loups"", ses ""leveurs de sorts"". George Sand elle-même, qui aimait passionnément ce Berry, transcrivit des dizaines de ces légendes dans ses romans. Aujourd'hui, les terrasses de café ont remplacé les rites nocturnes.","Stand in the middle of Place Gordaine, framed by towering timber-framed houses. By day a bustling medieval trade square; by night the legendary haunt of Berry wanderers and spectral lore.","La place Gordaine tire son nom de 'Gordina', lié au marché de la laine et du bétail. Ses maisons aux façades ouvragées témoignent de l'art des charpentiers après le sinistre de 1487. Mais dans l'imaginaire du Berry, terre réputée pour ses sorciers et jeteurs de sorts, la place Gordaine était considérée comme le carrefour des quatre vents : tout ce qui se disait ici était instantanément entendu par les êtres de l'invisible. Plusieurs procès en sorcellerie instruits à Bourges au XVIe siècle évoquent des réunions nocturnes à la lueur des torches au carrefour Gordaine avant les sabbats des marais.",https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Bourges_Place_Gordaine.jpg/800px-Bourges_Place_Gordaine.jpg
13,Jardin de l'Archevêché & Le Méridien Secret,47.0801,2.4008,NATURE,"Jardin classique dessiné selon les plans des élèves de Le Nôtre, offrant une perspective époustouflante sur l'abside de la cathédrale.","Classical French gardens designed in Le Nôtre's tradition, providing a breathtaking view of the cathedral's apse.","Le Jardin de l'Archevêché est l'une des plus belles surprises de Bourges — un espace de fraîcheur et de sérénité directement au pied de la cathédrale gothique. Mais ce jardin a une histoire beaucoup plus ancienne et secrète qu'il n'y paraît.

Ce terrain faisait à l'origine partie des vastes propriétés du palais de l'archevêque de Bourges, dont l'histoire remonte au treizième siècle. Il fut dessiné au début du dix-huitième siècle, vers 1730, par un élève du célèbre André Le Nôtre — l'architecte des jardins de Versailles. Il prit naturellement le nom du grand bâtiment qui lui faisait face, la résidence des archevêques.

Il s'organise autour d'un boulingrin, pelouse en creux encadrée de massifs colorés et de beaux arbres, selon un principe très rare dans les jardins à la française. Il se divise en deux parties : la première, géométrique et fleurie à la manière classique ; la seconde, boisée, s'organise en étoile forestière autour d'un kiosque à musique de 1908, qui résonne encore aux bals dominicaux d'été.

Ce qui est moins connu : les fouilles archéologiques menées dans ce jardin ont mis au jour des vestiges gallo-romains significatifs, ainsi que les fondations d'anciens bâtiments religieux disparus. Certains géobiologistes affirment que l'axe principal du jardin correspond à la ligne méridienne naturelle de la colline d'Avaricum, celle que les druides celtes utilisaient pour leurs calculs astronomiques avant même l'arrivée des Romains.

À deux pas du jardin s'élevait autrefois une grosse tour de défense de la ville, compagne muette de la cathédrale pendant des siècles. Aujourd'hui, le kiosque centenaire offre l'une des plus belles vues de Bourges. Il convient de prendre le temps d'y flâner.","Walk through the serene pathways of the Archbishop's Garden. Laid out in the seventeenth century, this classical park gives the most staggering perspective of Saint-Étienne's flying buttresses.","Au cœur du jardin de l'Archevêché, une fontaine centrale et des axes géométriques parfaits masquent une réalité plus ancienne : ce plateau abritait les thermes et les casernes romaines de la garnison d'Avaricum. Au XIXe siècle, les géomètres ont découvert qu'une ligne méridienne invisible relie le point culminant du jardin directement au centre de l'autel de la cathédrale et au puits de la crypte. Ce tracé sacré correspond aux courants telluriques majeurs traversant le Berry, réputés apaiser l'esprit de ceux qui y méditent au lever du soleil.",https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Bourges_Jardin_Archeveche.jpg/800px-Bourges_Jardin_Archeveche.jpg
14,Halle au Blé & Le Trésor des Dîmes,47.0872,2.3952,PALAIS,"Monumentale halle métallique et pierre du XIXe siècle, érigée sur l'ancienne place du marché aux grains du Berry.","Monumental grain hall combining stone and iron architecture, standing on the historic grain trading grounds.","La Halle au Blé de Bourges est un témoin architectural de la richesse agricole d'une région que l'histoire a longtemps surnommée ""le grenier de la France"". Le Berry, avec ses vastes plaines céréalières, fut pendant des siècles l'un des plus grands producteurs de blé du royaume.

Cette halle médiévale fut construite pour accueillir le marché au grain qui faisait la prospérité économique de Bourges. La ville était un nœud commercial majeur, à l'intersection des routes reliant Paris au Midi et les provinces atlantiques à la Bourgogne. Chaque saison, des marchands venus de toute la France venaient acheter et vendre les céréales berrichonnes, sous la charpente de la halle qui les protégeait des caprices du ciel.

Ce commerce du grain était aussi l'occasion d'un trafic plus discret mais tout aussi lucratif : le change des monnaies. Des changeurs s'installaient dans les encoignures de la halle, et certains profitaient du brouhaha du marché pour proposer des pièces douteuses ou des transactions financières à la limite de la légalité. L'Argentier Jacques Cœur lui-même avait commencé sa carrière dans ce milieu trouble des marchands et changeurs berruyers.

Le trésor des dîmes — l'impôt prélevé par l'Église sur les récoltes — était stocké dans les caves de la ville lors des grandes foires. La légende dit que certains de ces dépôts ne furent jamais récupérés lors des périodes troublées et qu'ils reposent encore quelque part sous les vieilles dalles de Bourges. Des fouilles menées dans les caves des maisons médiévales du quartier ont parfois révélé des corridors mystérieux conduisant vers des endroits inconnus.","Bourges' Corn Hall embodies the agricultural bounty of the Berry province. Its striking 19th-century glass and iron structure occupies grounds where grain was bartered since feudal times.","Sous les pavés de la Halle au Blé reposent de profondes caves voûtées où étaient entreposées les réserves de grains de la ville en cas de siège. Durant les guerres de religion au XVIe siècle, ces celliers souterrains servirent de cachette aux protestants pourchassés, puis de dépôt secret pour les monnaies frappées à l'atelier royal de Bourges. Des légendes tenaces rapportent que des sacs de florins et d'écus d'or y auraient été murés lors des émeutes de 1562 et n'auraient jamais été retrouvés.",https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Halle_au_bl%C3%A9_Bourges.jpg/800px-Halle_au_bl%C3%A9_Bourges.jpg
15,Château d'Eau & Le Réservoir des Souterrains,47.0782,2.3934,SOUTERRAINS,"Élégante rotonde néoclassique du XIXe siècle couronnant le système hydraulique et les galeries secrètes de la ville.","Neoclassical 19th-century water tower rotunda presiding over Bourges' ancient underground aqueduct network.","Ce château d'eau cylindrique en pierre calcaire de Charly est l'une des constructions les plus insolites du paysage urbain de Bourges. Il ressemble moins à un réservoir industriel qu'à un temple gréco-romain égaré dans la modernité.

Construit au dix-neuvième siècle pour alimenter la ville en eau courante, il surplombe un réseau souterrain que peu de Berruyers connaissent. Car sous Bourges se cache un véritable labyrinthe souterrain dont l'histoire remonte à l'époque gallo-romaine. Les ingénieurs romains d'Avaricum avaient creusé un aqueduc pour alimenter la ville en eau depuis des sources éloignées. Au Moyen Âge, ce réseau fut étendu et complété par des galeries servant à la fois à l'adduction d'eau, au stockage des denrées et, selon certaines sources, à des déplacements clandestins entre les monastères et la cathédrale.

Pendant les nombreuses périodes de conflits qui jalonnèrent l'histoire de Bourges — guerres de Religion, guerres civiles, occupations militaires — ces souterrains permirent à des habitants de se déplacer furtivement sous la ville. On raconte que des trésors d'archives religieuses et des objets précieux du Trésor de la cathédrale y furent dissimulés lors de la Révolution française pour les soustraire à la destruction.

Des tronçons de ces galeries ont été redécouverts au cours de travaux du vingtième siècle. Certains sont murés depuis des siècles et les géologues estiment que le réseau complet court sur plusieurs kilomètres sous les rues de la vieille ville. Le château d'eau, perché au-dessus de ce dédale, est le sentinelle silencieux d'un monde souterrain qui garde encore bien des secrets.","This neoclassical stone rotunda looks like a Roman temple. Erected in 1865 to supply drinking water, it intersects the vast subterranean quarries and tunnels running beneath Bourges.","Bourges repose sur un véritable gruyère de calcaire lacustre. Depuis l'époque gauloise et romaine, les hommes ont creusé sous la cité pour en extraire la belle pierre blanche des monuments. Ces carrières et galeries, reliées lors de la construction du château d'eau, constituent un dédale souterrain de plus de 40 kilomètres. Durant la Seconde Guerre mondiale, la Résistance berruyère y installa des imprimeries clandestines et des caches d'armes indétectables par l'occupant allemand.",https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Chateau_eau_Bourges.jpg/800px-Chateau_eau_Bourges.jpg
16,Maison de la Sorcière du Berry (Rue Mirebeau),47.0862,2.3941,SORCELLERIE,"Maison médiévale préservée associée aux contes d'Inquisition, herbiers de guérisseuses et croyances occultes du Berry.","Preserved medieval timber house linked to Berry folklore, herbal healing traditions, and inquisitorial trials.","Vous voici rue Mirebeau, devant l'une des maisons les plus chargées de mystère du vieux Bourges. Cette étroite demeure à pans de bois symbolise à elle seule la réputation que le Berry a longtemps traînée comme un manteau de soufre : celle de ""la terre des sorciers"".

Le Berry fut en effet pendant des siècles réputé dans toute la France pour ses pratiques magiques, ses guérisseurs, ses diseurs de bonne aventure et ses jeteurs de sort. Les ""meneurs de loups"" — des hommes censés avoir le pouvoir de diriger les meutes sauvages — les ""leveurs de sorts"" et les ""rebouteux"" peuplaient les campagnes berrichonnes. L'écrivain George Sand, qui vécut dans ce Berry qu'elle aimait passionnément, transcrivit des dizaines de ces légendes dans ses romans.

La rue Mirebeau elle-même porte une part de cette mémoire sombre. À l'époque médiévale, elle longeait l'Yèvrette, rivière artificielle qui servait aux artisans de la teinture et du tannage — des métiers qui utilisaient des substances chimiques odorantes et étranges, faisant facilement penser à la sorcellerie aux yeux des habitants du quartier.

Mais c'est surtout la dimension féminine de la sorcellerie berrichonne qui est fascinante. Des femmes guérisseuses, herboristes, sages-femmes, détenant un savoir ancestral sur les plantes et les corps, furent régulièrement accusées de pacte avec le diable. Plusieurs procès en sorcellerie sont documentés à Bourges aux seizième et dix-septième siècles. La maison que vous regardez pourrait avoir abrité l'une d'entre elles. Les pierres ne parlent pas, mais elles se souviennent.","Stop by this narrow medieval dwelling. The Berry province was historically known as the heartland of French folk magic and herbalists who passed healing charms through generations.","Dans la mémoire rurale berrichonne immortalisée par George Sand, le 'panseux de secrets' et la 'sorcière' étaient indispensables à l'équilibre des villages. Cette maison de ville aurait abrité au XVIIe siècle une herboriste réputée capable de calmer le 'mauvais œil' et de prédire les naissances par la lecture des braises de cheminée. Condamnée par le tribunal ecclésiastique lors des grandes paniques de sorcellerie de 1605, elle disparut mystérieusement de son cachot la veille de son exécution, nourrissant la légende de son envol vers les marais.",https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Bourges_Rue_Bourbonnoux.jpg/800px-Bourges_Rue_Bourbonnoux.jpg
17,Prieuré Saint-Martin & La Dalle des Templiers,47.0881,2.3962,TEMPLIERS,"Vestiges monastiques dissimulant des marques de tâcherons templiers et la croix pattée de la commanderie du Berry.","Monastic remains concealing Templar stonemason carvings and the pattée cross of the Berry commandery.","Les vestiges que vous apercevez ici sont ce qui subsiste d'un ancien prieuré médiéval, l'un des nombreux établissements religieux qui faisaient autrefois de Bourges une ville-sanctuaire extraordinairement dense en lieux de piété et de pouvoir.

L'ordre des Templiers avait une présence significative dans le Berry. Les archives historiques révèlent que les Chevaliers du Temple possédaient plusieurs maisons dans et autour de Bourges depuis au moins 1170. La commanderie la plus importante de la région était celle des Bordes, à Jussy-le-Chaudrier, mais des maisons templières existaient à Francheville et à Bourges même. Ce réseau de commanderies contrôlait non seulement des terres et des fermages, mais aussi des routes commerciales reliant Paris à l'Espagne et à la Méditerranée.

En 1307, Philippe le Bel fit arrêter tous les Templiers de France en une seule nuit. Leur procès, qui dura sept ans, fut l'un des plus extraordinaires de l'histoire médiévale. Le dernier Grand Maître, Jacques de Molay, fut brûlé vif à Paris en 1314 après avoir lancé une malédiction sur le roi et le pape. Dans les mois qui suivirent, les deux hommes moururent effectivement.

Ce qui fascine les historiens et les ésotéristes : le trésor considérable des Templiers — leurs archives, leurs manuscrits, leur or accumulé depuis deux siècles de croisades — n'a jamais été retrouvé. Les théories se multiplient sur ses caches possibles. Certaines traditions situent une partie de ce trésor dans les souterrains de villes-clés du réseau templier. Bourges, avec ses caves et galeries souterraines, est l'une des candidates évoquées.","Stand near the vestiges of the ancient Priory of Saint-Martin, historic crossroads for Templar and Hospitaller knights who maintained strong ties across the Berry province.","L'Ordre du Temple entretenait des liens étroits avec les chanoines de Bourges au XIIe et XIIIe siècles. Sur certaines pierres de seuil de ce secteur, on peut encore repérer des croix pattées gravées à la pointe et des monogrammes mariaux inversés. Lors de l'arrestation tragique des Templiers le vendredi 13 octobre 1307 ordonnée par Philippe le Bel, les chevaliers de Bourges auraient évacué leurs archives secrètes et leurs reliques à travers le réseau souterrain vers la forêt de Tronçais.",https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Prieure_Saint_Martin_Bourges.jpg/800px-Prieure_Saint_Martin_Bourges.jpg
18,Grange des Dîmes & Entrée des Galeries Célestines,47.0906,2.3865,SOUTERRAINS,"Ancien entrepôt ecclésiastique fortifié marquant l'un des accès secrets aux galeries souterraines militaires de Bourges.","Fortified tithe barn marking one of the historic entry points into Bourges' secret subterranean military tunnels.","Cette grange fortifiée médiévale, aux murs épais et aux contreforts imposants, témoigne d'une réalité économique que l'on oublie souvent : avant la Révolution française, l'Église prélevait sur chaque récolte du Berry un impôt en nature appelé la dîme — littéralement un dixième de la production agricole.

Pour stocker ces quantités considérables de céréales, de vin et de denrées diverses, les chapitres cathédraux et les prieurés disposaient de granges spécialement conçues : solides, sèches, bien ventilées et suffisamment vastes pour accueillir la production de dizaines de paroisses. Celle-ci était l'un des greniers des dîmes de la cathédrale de Bourges.

Mais cette grange cache une histoire bien plus secrète. Sa cave, aux voûtes romanes encore visibles, communiquait autrefois avec un réseau de galeries souterraines. Ces galeries sont liées à la présence médiévale du couvent des Célestins de Bourges, un ordre fondé par le pape Célestin Cinq en 1294. Les Célestins, moines d'une grande richesse spirituelle et parfois matérielle, entretenaient comme beaucoup d'ordres religieux un réseau de caves et de couloirs sous les villes où ils s'installaient.

La topographie du quartier laisse penser que plusieurs de ces galeries sont encore partiellement intactes sous les rues actuelles. Des sondages géophysiques discrets ont confirmé l'existence de cavités à plusieurs endroits du secteur. Comme dans beaucoup de cités médiévales françaises, le Bourges visible n'est que la surface d'un Bourges souterrain dont on ignore encore toute l'étendue. Les Célestins eux-mêmes cultivaient un goût pour le mystère, l'étude des textes hermétiques et la quête de la connaissance divine.","This fortified medieval tithe barn sheltered church dues. Deep inside its cellar lies an iron door opening into the legendary Celestine military gallery network.","Les Galeries Célestines constituent la partie la plus spectaculaire des souterrains militaires de Bourges. Longues de plusieurs centaines de mètres, taillées à coup de pic dans le roc dur, elles permettaient aux arquebusiers de Charles VII de surprendre les assiégeants à revers. Des niches taillées dans la roche témoignent encore de l'emplacement des lampes à huile et des dépôts de poudre noire.",https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Crypte_Cathedrale_Bourges.jpg/800px-Crypte_Cathedrale_Bourges.jpg
19,Église Saint-Bonnet & La Flamme Perpétuelle,47.0869,2.4011,CATHEDRAL,"Édifice gothique flamboyant aux somptueux vitraux du XVIe siècle attribués au maître verrier Jean Lecuyer.","Flamboyant Gothic church adorned with magnificent 16th-century stained glass windows by master Jean Lecuyer.","L'Église Saint-Bonnet est l'un des édifices religieux les plus anciens et les plus discrets de Bourges, nichée dans un quartier qui conserve encore l'atmosphère tranquille d'autrefois. Elle est dédiée à saint Bonnet, évêque de Clermont en Auvergne, né vers 623 et mort en 710, dont le culte était très répandu dans le Berry médiéval.

L'édifice actuel fut reconstruit au seizième siècle après que le terrible incendie de la Madeleine de 1487 eut ravagé le quartier qui portait son nom. Une première église Saint-Bonnet existait ici dès le haut Moyen Âge. Le quartier Saint-Bonnet était au Moyen Âge l'un des quartiers artisanaux les plus actifs de Bourges, peuplé de tanneurs, de cordonniers et de travailleurs du cuir qui utilisaient l'eau de l'Yèvrette.

Ce qui frappe dans cette église, c'est sa pénombre quasi mystique à certaines heures. Selon une tradition locale persistante, une lampe, appelée la ""flamme perpétuelle"", aurait brûlé sans interruption dans cette église pendant des siècles, entretenue par des dévots du quartier. Cette flamme symbolisait la prière continue de la communauté, veillant sur les vivants et les morts.

La particularité de saint Bonnet dans la hagiographie berrichonne : il est l'un des saints auxquels on attribue le pouvoir de guérir certaines maladies de la tête et des yeux. Des pèlerinages locaux s'y déroulaient encore au dix-neuvième siècle. Dans les arcanes de la tradition populaire berrichonne, ce saint était aussi invoqué par les femmes pour favoriser les naissances heureuses. L'église conserve plusieurs ex-votos témoignant de grâces obtenues par ses fidèles.","Saint-Bonnet Church showcases sensational 16th-century Flamboyant Gothic stained glass crafted by master artisan Jean Lecuyer, celebrated for ruby-red and luminous cobalt hues.","Les maîtres-verriers de Bourges possédaient une formule de coloration secrète pour obtenir un rouge pourpre inaltérable au soleil, obtenue par l'adjonction d'or colloïdal en fusion dans le verre en fusion. Cette technique, héritée directement des alchimistes arabes, était jalousement protégée sous serment corporatif. On disait que regarder le lever du soleil à travers le vitrail de saint Bonnet conférait l'apaisement des tourments de l'âme.",https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Bourges_Eglise_Saint-Bonnet.jpg/800px-Bourges_Eglise_Saint-Bonnet.jpg
20,Porte des Étoiles & L'Alignement Solsticial,47.079,2.4009,ALCHIMIE,"Portique en pierre sculpté d'astres et de symboles cosmiques marquant l'alignement solaire du solstice d'hiver à Bourges.","Historic stone portal carved with star constellations marking the winter solstice alignment across Bourges.","Vous êtes à la Porte des Étoiles, vestige d'un passé astronomique et ésotérique que peu de visiteurs soupçonnent. Ce nom mystérieux évoque l'une des traditions les plus fascinantes de la Bourges médiévale et renaissante : l'astronomie comme discipline secrète et divine.

Bourges fut au quinzième siècle l'une des villes de France où les savoirs astronomiques et astrologiques étaient le plus activement cultivés. Le contexte politique y contribuait : pendant la guerre de Cent Ans, la cour de Charles Sept réfugiée à Bourges s'entoura de savants, d'astrologues et de mathématiciens. L'Horloge Astronomique de la cathédrale, commandée en 1424 par ce même Charles Sept, n'était pas un simple ornement : elle était l'instrument de consultation des astres avant toute décision politique ou militaire importante.

La tradition dit que plusieurs demeures du quartier abritaient des astronomes et des astrologues qui observaient le ciel depuis leurs tours et leurs terrasses. Un alignement remarquable a été repéré par des chercheurs contemporains : certains des édifices gothiques et renaissants de Bourges semblent disposés selon des axes astronomiques liés aux levers et couchers du Soleil aux solstices d'été et d'hiver.

Au solstice d'hiver, le vingt-et-un décembre, un phénomène remarquable se produirait à certains endroits de la vieille ville : des rayons de soleil couchant traversent des ouvertures précisément orientées pour illuminer des motifs sculptés à des moments spécifiques de l'année. Ce type d'archéoastronomie a été documenté dans de nombreuses cités médiévales européennes. Bourges, avec ses multiples édifices orientés, attend encore l'étude exhaustive qui révélera ses alignements cachés.","Welcome to the Gate of Stars, a portal aligned with the winter solstice sunrise that projects light directly across to Saint-Étienne's southern rose window.","Les bâtisseurs médiévaux de Bourges étaient d'immenses géomètres. Comme à Stonehenge ou à Chartres, les axes majeurs de la ville ont été conçus en résonance avec les cycles cosmiques. La Porte des Étoiles témoigne de cette science oubliée où l'architecture terrestre devenait le miroir fidèle des constellations célestes.",https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Bourges_Cathedrale_Saint-Etienne_01.jpg/800px-Bourges_Cathedrale_Saint-Etienne_01.jpg`;

// Convert to semicolon-delimited standard format for Excel / CsvManager
function convertToSemicolonCsv(csv) {
  const rows = [];
  let currentRow = [];
  let currentField = '';
  let inQuotes = false;
  let i = 0;

  while (i < csv.length) {
    const char = csv[i];
    if (inQuotes) {
      if (char === '"') {
        if (i + 1 < csv.length && csv[i + 1] === '"') {
          currentField += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else {
        currentField += char;
      }
    } else {
      if (char === '"') {
        inQuotes = true;
      } else if (char === ',') {
        currentRow.push(currentField);
        currentField = '';
      } else if (char === '\r') {
        // ignore
      } else if (char === '\n') {
        currentRow.push(currentField);
        currentField = '';
        if (currentRow.some(c => c.trim().length > 0)) {
          rows.push(currentRow);
        }
        currentRow = [];
      } else {
        currentField += char;
      }
    }
    i++;
  }
  if (currentField.length > 0 || currentRow.length > 0) {
    currentRow.push(currentField);
    if (currentRow.some(c => c.trim().length > 0)) {
      rows.push(currentRow);
    }
  }

  // Format as semicolon-delimited CSV with UTF-8 BOM
  const escapeSemi = (val) => {
    if (!val) return '';
    const str = String(val);
    if (str.includes(';') || str.includes('"') || str.includes('\n') || str.includes('\r')) {
      return '"' + str.replace(/"/g, '""') + '"';
    }
    return str;
  };

  return rows.map(r => r.map(escapeSemi).join(';')).join('\n') + '\n';
}

const semiColonCsv = convertToSemicolonCsv(rawCsv);

// UTF-8 BOM
const bom = Buffer.from([0xEF, 0xBB, 0xBF]);
const buffer = Buffer.concat([bom, Buffer.from(semiColonCsv, 'utf8')]);

const dest1 = path.join(__dirname, 'app', 'src', 'main', 'assets', 'poi_export.csv');
const dest2 = path.join(__dirname, 'bourges_points_interet.csv');

fs.writeFileSync(dest1, buffer);
fs.writeFileSync(dest2, buffer);

console.log('Successfully wrote enriched CSVs with UTF-8 BOM:');
console.log(' - ' + dest1);
console.log(' - ' + dest2);
